<?php
/**
 * Modifie le comportement par défaut de Wysiwyg pour ajouter un JS contenant
 * une liste de styles applicables sur CKEditor
 */
function wysiwyg_custom_styles_wysiwyg_editor_settings_alter(&$settings, $context) {
    if ($context['profile']->editor == 'ckeditor') {
        $settings['stylesCombo_stylesSet'] = 'my_styles:' . base_path() . drupal_get_path('module', 'wysiwyg_custom_styles').'/wysiwyg_styles.js';
    }
}
?>
